# Generated by Django 3.0.8 on 2022-05-13 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20, '20자 이상 작성할 수 없습니다')]),
        ),
    ]
