# Generated by Django 3.0.8 on 2022-03-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='follower',
            name='status',
            field=models.CharField(default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='following',
            name='status',
            field=models.CharField(default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='liking',
            name='status',
            field=models.CharField(default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(default='valid', max_length=20),
        ),
    ]
