# Generated by Django 3.0.8 on 2022-05-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220505_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liking',
            old_name='profile',
            new_name='user',
        ),
    ]
