# Generated by Django 3.0.8 on 2022-04-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_change_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alttext',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentlke',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentlke',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='hashtag',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='user_id',
            new_name='user',
        ),
    ]
