# Generated by Django 3.0.8 on 2022-04-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
