# Generated by Django 3.0.8 on 2022-03-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_allow_null_of_Profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Location'),
        ),
    ]
