# Generated by Django 3.0.8 on 2022-04-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003___str__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.BigIntegerField(null=True),
        ),
    ]
